version: '3.8'

services:
  web:
    build: .
    image: doc-n-process-ai:latest # Optional: Use a specific image tag
    container_name: ot-synapse-ai
    command: sh -c "uvicorn doc-n-process-ai_app:app --host 0.0.0.0 --port 6060"
    # command: sh -c "python doc-ai_app.py"
    env_file:
      - .env
    ports:
      - 6060:6060
    volumes:
      - .:/app
  
  qdrant:
    image: qdrant/qdrant:v1.3.5  # Replace with the desired Qdrant version
    container_name: qdrant
    ports:
      - "6333:6333"  # Map the host port to the Qdrant container port
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: